package com.sunsafe.app.presentation.screens.report

import android.content.Intent
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.core.content.FileProvider
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.sunsafe.app.presentation.theme.SunSafeColors
import com.sunsafe.app.presentation.viewmodel.HistoryViewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReportScreen(
    onBack: () -> Unit,
    viewModel: HistoryViewModel = hiltViewModel()
) {
    val state by viewModel.uiState.collectAsStateWithLifecycle()
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    var isGenerating by remember { mutableStateOf(false) }
    var generated by remember { mutableStateOf(false) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Exposure Report") },
                navigationIcon = { IconButton(onClick = onBack) { Icon(Icons.Filled.ArrowBack, null) } }
            )
        }
    ) { padding ->
        LazyColumn(
            Modifier.fillMaxSize().padding(padding).padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp),
            contentPadding = PaddingValues(vertical = 8.dp)
        ) {
            item {
                Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(20.dp),
                    colors = CardDefaults.cardColors(containerColor = SunSafeColors.SunOrange.copy(alpha = 0.1f))) {
                    Column(Modifier.padding(24.dp), horizontalAlignment = Alignment.CenterHorizontally,
                        verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text("📊", style = MaterialTheme.typography.displaySmall)
                        Text("30-Day Sun Exposure Report", style = MaterialTheme.typography.titleLarge,
                            fontWeight = FontWeight.Bold)
                        Text("Generate a comprehensive PDF report of your UV exposure history.",
                            style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                }
            }

            // Summary stats
            item {
                Text("Report Summary", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
            }
            item {
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    ReportStatCard("Days Tracked", "${state.dailySummaries.size}", Modifier.weight(1f))
                    ReportStatCard("Total Exposure", "${state.totalExposureMinutes.toInt()} min", Modifier.weight(1f))
                }
            }
            item {
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    ReportStatCard("Total Sessions", "${state.totalSessions}", Modifier.weight(1f))
                    ReportStatCard("Burn Incidents", "${state.burnIncidents}", Modifier.weight(1f))
                }
            }

            // What's included
            item {
                Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(16.dp)) {
                    Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text("Report Includes:", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.SemiBold)
                        listOf(
                            "✅ Skin type and profile summary",
                            "✅ Day-by-day exposure breakdown",
                            "✅ UV index peaks and trends",
                            "✅ Sunscreen application log",
                            "✅ Burn incidents",
                            "✅ Personalised recommendations"
                        ).forEach { item ->
                            Text(item, style = MaterialTheme.typography.bodySmall)
                        }
                    }
                }
            }

            item {
                Button(
                    onClick = {
                        scope.launch {
                            isGenerating = true
                            withContext(Dispatchers.IO) {
                                generateAndSharePdf(context, state.dailySummaries,
                                    state.totalExposureMinutes, state.burnIncidents)
                            }
                            isGenerating = false
                            generated = true
                        }
                    },
                    enabled = !isGenerating,
                    modifier = Modifier.fillMaxWidth().height(56.dp),
                    colors = ButtonDefaults.buttonColors(containerColor = SunSafeColors.SunOrange),
                    shape = RoundedCornerShape(16.dp)
                ) {
                    if (isGenerating) {
                        CircularProgressIndicator(Modifier.size(20.dp), color = androidx.compose.ui.graphics.Color.White, strokeWidth = 2.dp)
                        Spacer(Modifier.width(8.dp))
                        Text("Generating…")
                    } else {
                        Icon(Icons.Filled.PictureAsPdf, null); Spacer(Modifier.width(8.dp))
                        Text("Generate & Share PDF")
                    }
                }
            }

            if (generated) {
                item {
                    Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(12.dp),
                        colors = CardDefaults.cardColors(containerColor = SunSafeColors.SafeGreen.copy(alpha = 0.1f))) {
                        Row(Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            Icon(Icons.Filled.CheckCircle, null, tint = SunSafeColors.SafeGreen)
                            Text("PDF shared successfully!", style = MaterialTheme.typography.bodyMedium, color = SunSafeColors.SafeGreen)
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun ReportStatCard(label: String, value: String, modifier: Modifier = Modifier) {
    Card(modifier, shape = RoundedCornerShape(12.dp)) {
        Column(Modifier.padding(16.dp).fillMaxWidth(), horizontalAlignment = Alignment.CenterHorizontally) {
            Text(value, style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)
            Text(label, style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
    }
}

private fun generateAndSharePdf(
    context: android.content.Context,
    summaries: List<com.sunsafe.app.domain.model.DailySummary>,
    totalMinutes: Double,
    burnCount: Int
) {
    val pdfDocument = PdfDocument()
    val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4
    val page = pdfDocument.startPage(pageInfo)
    val canvas = page.canvas

    val titlePaint = Paint().apply { textSize = 24f; isFakeBoldText = true; color = android.graphics.Color.parseColor("#FF6D00") }
    val bodyPaint = Paint().apply { textSize = 12f; color = android.graphics.Color.DKGRAY }
    val headerPaint = Paint().apply { textSize = 14f; isFakeBoldText = true; color = android.graphics.Color.BLACK }
    val smallPaint = Paint().apply { textSize = 10f; color = android.graphics.Color.GRAY }

    var y = 60f
    canvas.drawText("SunSafe — UV Exposure Report", 40f, y, titlePaint)
    y += 30f

    val sdf = SimpleDateFormat("MMMM dd, yyyy", Locale.getDefault())
    canvas.drawText("Generated: ${sdf.format(Date())}", 40f, y, smallPaint)
    y += 30f

    // Divider
    canvas.drawLine(40f, y, 555f, y, bodyPaint.also { it.strokeWidth = 1f })
    y += 20f

    // Summary
    canvas.drawText("30-Day Summary", 40f, y, headerPaint)
    y += 20f
    canvas.drawText("Total exposure: ${totalMinutes.toInt()} minutes across ${summaries.size} days", 40f, y, bodyPaint)
    y += 18f
    canvas.drawText("Burn incidents: $burnCount", 40f, y, bodyPaint)
    y += 30f

    // Daily breakdown
    canvas.drawText("Daily Breakdown", 40f, y, headerPaint)
    y += 20f

    val daySdf = SimpleDateFormat("EEE MMM d", Locale.getDefault())
    summaries.take(25).forEach { summary ->
        if (y > 800f) return@forEach
        val dateStr = daySdf.format(Date(summary.date))
        val line = "$dateStr  |  ${summary.totalExposureMinutes.toInt()}min  |  UV peak: ${summary.uvIndexPeak.toInt()}${if (summary.burned) "  🔥 BURN" else ""}"
        canvas.drawText(line, 40f, y, bodyPaint)
        y += 16f
    }

    y += 20f
    canvas.drawLine(40f, y, 555f, y, bodyPaint)
    y += 20f
    canvas.drawText("Recommendations:", 40f, y, headerPaint)
    y += 18f
    canvas.drawText("• Always apply SPF 30+ when UV index is 3 or above.", 40f, y, bodyPaint)
    y += 16f
    canvas.drawText("• Reapply sunscreen every 2 hours when outdoors.", 40f, y, bodyPaint)
    y += 16f
    canvas.drawText("• Seek shade between 10am and 4pm during high UV.", 40f, y, bodyPaint)
    y += 30f
    canvas.drawText("This report is for informational purposes only. Consult a dermatologist for medical advice.", 40f, y, smallPaint)

    pdfDocument.finishPage(page)

    // Save to cache
    val file = File(context.cacheDir, "SunSafe_Report_${System.currentTimeMillis()}.pdf")
    pdfDocument.writeTo(FileOutputStream(file))
    pdfDocument.close()

    // Share via intent
    val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
    val intent = Intent(Intent.ACTION_SEND).apply {
        type = "application/pdf"
        putExtra(Intent.EXTRA_STREAM, uri)
        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
    }
    context.startActivity(Intent.createChooser(intent, "Share SunSafe Report").also {
        it.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
    })
}
